version: '3.8'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://db:5432/keycloak
      - KC_DB_USERNAME=keycloak
      - KC_DB_PASSWORD=password
    ports:
      - "8081:8080"
    depends_on:
      - db
    command: start-dev
    networks:
      - app-network

  db:
    image: postgres:16
    environment:
      - POSTGRES_DB=keycloak
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=password
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - app-network

  upload-proxy:
    build:
      context: ./upload-proxy
      dockerfile: Dockerfile
    environment:
      - KEYCLOAK_URL=http://keycloak:8080
      - KEYCLOAK_REALM=upload-realm
      - CLIENT_ID=upload-client
      - CLIENT_SECRET=dYhBaLvJ2vLQIZ487nZQCMWyVETwvOqj
      - JWT_AUDIENCE=account,upload-client
      - BACKEND_PORT=3000
      - UPLOADS_DIR=/app/uploads
      - METADATA_FILE=/app/uploads.json
      - ALLOWED_ORIGINS=http://localhost:8000,http://127.0.0.1:8000
      - RUST_LOG=info
    ports:
      - "3000:3000"
    volumes:
      - ./uploads:/app/uploads
      - ./uploads.json:/app/uploads.json
    depends_on:
      - keycloak
    networks:
      - app-network



volumes:
  db-data:

networks:
  app-network:
    driver: bridge