name: Full Stack Workflow

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  basic-check:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Check project structure
      run: |
        if [ -d "frontend" ] && [ -d "upload-proxy" ] && [ -d "keycloak" ]; then
          echo "✅ Project structure looks good"
        else
          echo "❌ Missing required directories"
          exit 1
        fi
        
    - name: Check Docker Compose
      run: |
        if [ -f "docker-compose.yml" ]; then
          docker-compose config
          echo "✅ Docker Compose is valid"
        else
          echo "❌ docker-compose.yml missing"
          exit 1
        fi
        
    - name: Check required files
      run: |
        required_files=("README.md" "flow.md")
        for file in "${required_files[@]}"; do
          if [ -f "$file" ]; then
            echo "✅ $file exists"
          else
            echo "❌ $file missing"
            exit 1
          fi
        done
        
    - name: Check YAML formatting
      run: |
        echo "Checking YAML formatting..."
        
        # Check docker-compose.yml formatting
        if [ -f "docker-compose.yml" ]; then
          # Basic YAML syntax check
          python3 -c "
import yaml
try:
    with open('docker-compose.yml', 'r') as f:
        yaml.safe_load(f)
    print('✅ docker-compose.yml is valid YAML')
except Exception as e:
    print(f'❌ docker-compose.yml has YAML errors: {e}')
    exit(1)
"
        fi
